name: kiss_firebase_repository_rest
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/leehiggins/kiss_firebase_repository_rest

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  kiss_repository: ^0.7.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
