name: kiss_firebase_repository_rest
description: A lightweight, type-safe Firestore implementation of the KISS Repository pattern for Dart using the Google Cloud Firestore REST API
version: 0.2.0
repository: https://github.com/leehiggins/kiss_firebase_repository_rest

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.3.0
  kiss_repository: ^0.12.0
  meta: ^1.15.0


dev_dependencies:
  build_runner: ^2.4.13
  cloud_firestore: ^5.6.8
  firebase_core: ^3.10.0
  lints: ^5.0.0
  test: ^1.24.0
  very_good_analysis: ^9.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
